version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run:
          name: install npm
          command: npm install
      - run:
          name: Run NPM Tests
          command: npm test
      - run:
          name: Generate Code Coverage Report
          command: npm run coverage
      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: /tmp/coverage

workflows:
  calculator:
    jobs:
      - build
