version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:16
    steps:
      - checkout
      - run:
          name: install npm
          command: npm install
      - run:
          name: Run NPM Tests
          command: npm run test:coverage
      - run:
          name: Generate Code Coverage Report
          command: npm run coverage
      - store_test_results:
          path: .circleci/test-results
      - store_artifacts:
          path: .circleci/coverage

workflows:
  version: 2.1
  calculator:
    jobs:
      - build
